annotations:
    artifacthub.io/containsSecurityUpdates: "true"
apiVersion: v2
appVersion: V1.0
description: 'Het Review Component faciliteert reviews van resources, hoewel we hierbij in eerste instantie denken aan producten vanuit het PDC zou een resource in feite alles kunnen zijn. Onder een review verstaan we een gebruikerservaring, deze ervaring kan zowel worden aangeduid met een cijfer als een een textuele beschrijving. Additioneel biedt het component ondersteuning voor “likes” en het berekenen van totale gemiddelde review resultaten op resources.'
name: review-component
version: 1.0.0
home: https://www.conduction.nl
icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
keywords:
    - commonground
    - haven
    - nlx
    - component
maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
      condition: redis.enabled