apiVersion: v1
entries:
  rc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-09T11:35:35.354529043Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 114e25259cede3786c1b17daa9f95c9ee182c26b9d8edad6c675471b13b627dc
    home: rc.zaakonline.nl
    icon: rc.zaakonline.nl
    name: rc
    urls:
    - rc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-09T11:35:35.34559914Z"
